CREATE TABLE USUARIOS (
    CD_USUARIO NUMBER(7) NOT NULL,
    NM_USUARIO VARCHAR2(60) NOT NULL,
    ENDERECO VARCHAR2(60) NOT NULL,
    BAIRRO VARCHAR2(50) NOT NULL,
    UF VARCHAR2(2) NOT NULL,
    CONSTRAINT PK_USUARIOS PRIMARY KEY (CD_USUARIO)
);

CREATE TABLE USUARIO_GRUPO (
    CD_USUARIO NUMBER(7),
    CD_GRUPO NUMBER(4),
    CONSTRAINT PK_USUARIO_GRUPO PRIMARY KEY (CD_USUARIO, CD_GRUPO)
);

CREATE TABLE CHAMADOS (
    ID_CHAMADO NUMBER(7) NOT NULL,
    DH_CHAMADO DATE,
    OCORRENCIA VARCHAR2(4000),
    CONSTRAINT PK_CHAMADOS PRIMARY KEY (ID_CHAMADO)
);

CREATE TABLE HIST_CHAMADOS (
    ID_CHAMADO NUMBER(7),
    HISTORICO VARCHAR2(4000),
    DH_HISTORICO DATE
);

CREATE TABLE TECNICOS (
    CD_TECNICO NUMBER(4),
    NM_TECNICO VARCHAR2(50), -- Corrigido o tamanho do NM_TECNICO
    CONSTRAINT PK_TECNICOS PRIMARY KEY (CD_TECNICO)
);

CREATE TABLE TIPO_CONEXAO (
    CD_TIP_CON NUMBER(2),
    DSC_TIP_CON VARCHAR2(30),
    VELOCIDADE NUMBER(5),
    CONSTRAINT PK_TIPO_CONEXAO PRIMARY KEY (CD_TIP_CON)
);

CREATE TABLE GRUPO_ACESSO (
    CD_GRUPO NUMBER(4),
    DS_GRUPO VARCHAR2(50),
    CONSTRAINT PK_GRUPO_ACESSO PRIMARY KEY (CD_GRUPO)
);